### PR TITLE
Changes for details screen

### PR DESCRIPTION
**Pull request by kchitalia**

### CODE REVIEW

**Comment by kchitalia** [comment]
Sorry, there are a lot of changes here. But this will get the details screen working.

**Comment by bhariharan** [comment]
:+1:

**Comment by wmathurin** [comment]
I don't think we shouldn't check in the dependencies.
Instead you should have a readme file with the steps to follow (e.g. running bower install) after cloning the repo. Alternatively, you could have an install.sh script.

**Comment by kchitalia** [comment]
@wmathurin I'll address your feedback in a new pull request. This PR will help for the demo.

**Comment by wmathurin** [comment]
Now the repo is bloated with thousands of files that should never have been checked in.

**Comment by kchitalia** [comment]
I agree. I will be removing this in a separate pull request.

**Comment by wmathurin** [comment]
The repo won't shrink if you remove them later. When you clone a repo, you get the whole history.

**Comment by bhariharan** [comment]
Perhaps we could do a rollback of the previous commit and a force push. This will overwrite the history.

**Pull request merged**
