### PR TITLE
Add submodule to mobile-ui-elements and update html pages

### PR DESCRIPTION
**Pull request by kchitalia**
@wmathurin I added the submodule and symbolic links.

### CODE REVIEW

**Comment by bhariharan** [comment]
Looks okay to me.

**Comment by wmathurin** [comment]
:+1:

**Comment by wmathurin** [comment]
After logging in, no contacts are loaded (spinner never stops spinning) - that wasn't the case before the move to submodule. Did some changes get lost in the move?

**Comment by kchitalia** [comment]
Let me double check, I was able to see the contacts list.

**Pull request merged**
